apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hello-world
  namespace: hello-world-app
  labels:
    app: hello-world-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: file.csi.azure.com
    readOnly: false    
    volumeHandle: csi-test-109222               # [UNIQUE_VOLUME_ID] - make sure this volumeid is unique in the cluster. `#` is not allowed in self defined volumeHandle
    volumeAttributes:
      resourceGroup: azconf21demogroup          # [EXISTING_RESOURCE_GROUP_NAME] - optional, only set this when storage account is not in the `MC_` resource group
      storageAccount: azcconf21demostorage      # [EXISTING_STORAGE_ACCOUNT-NAME]
      shareName: azcconf21demoshare             # [EXISTING_FILE_SHARE_NAME] - only file share name, don't use full path
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hello-world
  namespace: hello-world-app
  labels:
    app: hello-world-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-hello-world
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
  namespace: hello-world-app
  labels:
    app: hello-world-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: busybox
        image: busybox:1.30.1
        args: ["/bin/sh", "-ec", "SLEEP_TIMEOUT=60;while :; do echo sleeping for $SLEEP_TIMEOUT seconds...; sleep $SLEEP_TIMEOUT ; done"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: file-storage
          mountPath: /data
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: pvc-hello-world